### ISSUE TITLE
Add checks to prevent the same `Conditional` from being used multiple times

### ISSUE THREAD

**Issue by mkorbel1** [intel/rohd#104]
## Motivation
If someone uses the same `Conditional` object multiple times in the same `_Always` or in different `_Always` blocks, it can cause unexpected behavior and simulation/synthesis mismatches.

## Desired solution
There should be an explicit check that `Conditional`s are not reused.  Perhaps a build-time check where each `Conditional` is assigned a parent `_Always`, and the `_Always` confirms there are no duplicates within itself?

**Comment by quekyj** [comment]
@mkorbel1 I can pick this up as well.

**Comment by quekyj** [comment]
Check at the construction time.

**Comment by quekyj** [comment]
Conditional Object creation:
```
final condOne = If(a, then: [q < d]);
```

**Comment by quekyj** [comment]
Write a test 

```
final condone = If(a, then: [q < d]);
```

1. Put this condone in 2 conditionals block
2. Add a test.
