### ISSUE TITLE
Unique `Case` with multiple match behavior

### ISSUE THREAD

**Issue by mkorbel1** [intel/rohd#107]
## Motivation
When multiple cases match on a unique case statement, it currently causes an exception to be thrown.  Perhaps this should be a configurable option allowing X's to be driven instead.

## Desired solution
Always drive X when there's a violation of unique rules, and raise exception on it as well in a configurable way (default enabled) on a per-`Case` basis.

## Alternatives considered  
A global switch for this type of check could also be an option.

## Additional details
SystemVerilog by default just prints a warning message (http://www.verilogpro.com/systemverilog-unique-priority/) which seems not great.

**Comment by dmetis** [comment]
You can also sign me up for this.

**Comment by mkorbel1** [comment]
Sure, thanks!

If we do go the route of a global switch, I think it will be the first of its type, so perhaps there's some discussion to be had on the best way to do that.

**Comment by mkorbel1** [comment]
Because `Combinational` can execute "glitchy" behavior, there are plenty of scenarios where a "unique case statement" might temporarily violate uniqueness, but eventually settles to a unique value.  This means the exception behavior is not just potentially unpreferred, but actually functionally a bug.  I think we can just lean towards making it always send X, maybe with some logging (https://github.com/intel/rohd/issues/230).  If we want to add an exception (optionally?) it would have to listen for things to settle, which is not really desirable for combinational logic.  If we do it in sequential logic, we could maybe keep it, but then you have to keep context about whether it is in sequential or combinational logic.

**Comment by mkorbel1** [comment]
We need to adjust the other exception thrown in there for "no matching case" as well
