### ISSUE TITLE
Automatically extract/update the version of ROHD that generates things

### ISSUE THREAD

**Issue by mkorbel1** [intel/rohd#112]
## Motivation
It would be nice if the generated outputs (e.g. SystemVerilog, waveform dumps) had a guaranteed accurate version number of ROHD that generated them.  A version number (from pubspec.yaml) would be good, but even better would be to also include a git hash, so it can be determined exactly what generated the code.

## Desired solution
Find a reliable way to figure out git hash, release information, version number, etc. and inject it into generated code.

## Alternatives considered  
Currently information is either omitted or manually updated (error prone).

**Comment by quekyj** [comment]
Hi @mkorbel1, let me try to work on this.
