### ISSUE TITLE
In `SimCompare` calculate the `signalToWidthMap` instead of manually inputting in `iverilogVector`

### ISSUE THREAD

**Issue by mkorbel1** [intel/rohd#133]
## Motivation
It's annoying and confusing to need to set the `signalToWidth` map for `SimCompare` after already setting port widths properly.

## Desired solution
Remove the `signalToWidthMap` from `SimCompare.iverilogVector`, and instead calculate it based on the port widths of the module.

## Additional details
This change might be good to do along with the CIRCT branch merge.

**Comment by quekyj** [comment]
@mkorbel1 I think I can look into into this next.
