### ISSUE TITLE
Add a mechanism to reset all flops of a `Sequential`

### ISSUE THREAD

**Issue by mkorbel1** [intel/rohd#137]
## Motivation
"It's cumbersome and error prone to have to keep resetting flops I'm adding"

When creating lots of flops in a `Sequential`, often you want them all reset by the same reset signal.  It would be convenient to make that an option.

## Desired solution
An option in `Sequential` or a new type of sequential object that handles reset across all flops it creates.

## Alternatives considered  
Currently, each flop must be manually reset.

**Comment by RPG-coder-intc** [comment]
I will take a look into this issue 👍
