### ISSUE TITLE
Add `gt` and `gte` for consistency to `Logic`

### ISSUE THREAD

**Issue by mkorbel1** [intel/rohd#140]
## Motivation
For equality, less than, and less than or equal to, `Logic` has `eq`, `lt`, and `lte`, respectively, since those operators have different meanings (object equality, conditional assignment, and assignment, respectively).  Since greater than and greater than or equal to do not use those operators for something else, they were overloaded for `>` and `>=`.  However, this is a little inconsistent and confusing to new users.  It would be nice if you could also optionally use `gt` and `gte` for consistency.

## Desired solution
Add `gt` and `gte` implementations to `Logic`.  Do not remove `>` and `>=` overloaded operators.

**Comment by IdiBetzSch** [comment]
Hey. 

Picked this one up while familiarizing myself with Dart. Seems like I have it done(wasn't much to it), but running myself through the test and such getting a feel for the setup right now.

**Comment by Sanchit-kumar** [comment]
Picking this one up.
