### ISSUE TITLE
Implement `neq`

### ISSUE THREAD

**Issue by mkorbel1** [intel/rohd#148]
## Motivation
Equality checks with `eq` are simple, but you have to use `~...eq` for not-equal-to.  It would be nice to be able to do not-equal-to using `neq`.

## Desired solution
Implement `neq` everywhere that `eq` exists (for values and signals).

**Comment by stephtancs** [comment]
could take this too

**Comment by mkorbel1** [comment]
@stephtancs note @Sanchit-kumar has implemented this already here: https://github.com/intel/rohd/pull/350
