### ISSUE TITLE
`Const`s where `val` is a `LogicValue` have unsanitary names

### ISSUE THREAD

**Issue by mkorbel1** [intel/rohd#152]
## Describe the bug
If you create a `Const` where `val` is a `LogicValue` (or some other legal `val` whose `toString` produces an invalid variable name), then the generated `name` for the `Logic` can be invalid since it is not sanitized.  The name of the signal should be sanitized.

## To Reproduce
```dart
Const(LogicValue.ofString('10xz'))
```

## Expected behavior
Constant is created without exception.

## Actual behavior
Exception due to unsanitary name.

**Comment by aherrera97intl** [comment]
Will start working on this
