### ISSUE TITLE
Implement hardware arbiters

### ISSUE THREAD

**Issue by mkorbel1** [intel/rohd#154]
## Motivation
Hardware designers often need arbiters, it would be convenient if ROHD had some built in.

## Desired solution
Implement a configurable or set of arbiters, and/or other generation/abstraction capabilities for arbitration.

**Comment by aherrera97intl** [comment]
Will work on it

**Comment by mkorbel1** [comment]
These should be implemented in the ROHD Hardware Component Library (https://github.com/intel/rohd-hcl).

The first one is filed here: https://github.com/intel/rohd-hcl/issues/11
