### ISSUE TITLE
Make `signExtend` generate prettier SystemVerilog

### ISSUE THREAD

**Issue by mkorbel1** [intel/rohd#157]
## Motivation
Right now the `signExtend` genreates a mux, which is especially ugly when there's only 1 bit.  SystemVerilog has some nice syntax for repeating a signal value (replication operator) which could be nicer in the generated code.

## Desired solution
For example:
```SystemVerilog
logic x;

// instead of this
x[0] ? 8'hff : 8'h0

// do this
{8{x}}
```

There's special cases to consider for 1-bit values vs. >1-bit values, since you don't need to do `[0]` on a 1-bit signal to get the upper-most bit.

**Comment by akshay-wankhede** [comment]
@mkorbel1 can you please assign this to me?

**Comment by akshay-wankhede** [comment]
PR https://github.com/intel/rohd/pull/203 raised with the fix.
