### ISSUE TITLE
Outdated package "lints"

### ISSUE THREAD

**Issue by chykon** [intel/rohd#165]
The "lints" package has been updated to version 2.0.0, so ROHD is [using](https://github.com/intel/rohd/blob/03d5e5f398efeecd6e806615d9e9047c52ca8688/pubspec.yaml#L19) an outdated version.

Also I would suggest using a stricter set of rules. There is an [article](https://rydmike.com/blog_flutter_linting.html) comparing linting packages.

**Comment by mkorbel1** [comment]
Thanks for the link to the article.  I'm working on cleaning up a ton of lint issues with a bunch more rules based on the recommendations in the article.
