### ISSUE TITLE
Close code coverage on `LogicValue` code

### ISSUE THREAD

**Issue by mkorbel1** [intel/rohd#219]
### Motivation

There have been bugs found in `LogicValue` and its three implementations (small, big, filled), but not all the code is covered in existing unit tests.

### Desired solution

Write tests that cover the `LogicValue`-related code to 100% (or close to it)

**Comment by mkorbel1** [comment]
The new `LogicValue.of` unfortunately pushes this issue even farther in the wrong direction.
See https://github.com/intel/rohd/pull/375

**Comment by mjayasim9** [comment]
I will work on this.
