### ISSUE TITLE
`ReplicationOp` should support multi-bit replication

### ISSUE THREAD

**Issue by mkorbel1** [intel/rohd#223]
### Summary

PR https://github.com/intel/rohd/pull/203 introduced `ReplicationOp`, but only 1-bit `Logic`s are supported, it does support multi-bit `Logic`s.  

### To Reproduce

Use `ReplicationOp` with a multi-bit value for the `bit` input.

### Expected behavior

It's probably nice to support multi-bit, but requires a bit more logic to handle that.

**Comment by akshay-wankhede** [comment]
Please assign it to me
