### ISSUE TITLE
Expose `ReplicationOp` as a function on `Logic`

### ISSUE THREAD

**Issue by mkorbel1** [intel/rohd#224]
### Motivation

The replication operator is useful (introduced in https://github.com/intel/rohd/pull/203), but currently only can be instantiated by constructing a new `ReplicationOp`.  It would be nice to expose it as a function on `Logic` itself.

### Desired solution

Add some function on `Logic`, like `Logic.replicate(int multiplier)` or something like that.

### Additional details

Probably good to consider multi-bit handling at the same time, referenced here: https://github.com/intel/rohd/issues/223

**Comment by akshay-wankhede** [comment]
Please assign this issue to me
