### ISSUE TITLE
Implement a shorthand for case statements

### ISSUE THREAD

**Issue by mkorbel1** [intel/rohd#304]
### Motivation

Sometimes it's desirable to assign/create some signal based on some condition, similar to a `mux`, but there is more than one case to consider.  The current easy options could be either a chain of `mux`s, which implies priority, or building a `Case` in a `Conditional`, which is a little heavy-weight for a simple scenario.

It would be nice to have some automation that creates a `Conditional` and `Case`, optionally with the usual set of settings like `unique`.

### Desired solution

A function which builds a `Conditional` and `Case` statement with some simple set of inputs.  Probably it should only be capable of applying to a single signal (i.e. one output, like `mux`).  For more complex scenarios, people can just create the full thing themselves.

**Comment by mjayasim9** [comment]
I will work on this
