### ISSUE TITLE
Prevent `Logic` from connecting to itself

### ISSUE THREAD

**Issue by chykon** [intel/rohd#316]
### Describe the bug

`Logic` can be connected to itself, which is rather odd.

### To Reproduce

```dart
import 'package:rohd/rohd.dart';

void main() {
  final a = Logic();
  final b = Logic();

  a <= a;
  a <= b; // exception
}
```

### Expected behavior

Connecting `Logic` to itself is not allowed.

### Actual behavior

Connecting `Logic` to itself is allowed.

### Additional: Context

ROHD v0.4.2

**Comment by mkorbel1** [comment]
This represents a trivial case of a combinational loop.  It should be quite easy to detect statically, especially given `_Wire`s are shared among connected `Logic`s.  I am having trouble thinking of any valid use-case where a ring of wires connected directly to each other (including one to itself) would ever be valuable, so throwing an exception immediately seems fair to me.

Thank you for filing!
