### ISSUE TITLE
`WaveDumper` cannot create missing directories in the `outputPath` path

### ISSUE THREAD

**Issue by chykon** [intel/rohd#324]
### Describe the bug

`WaveDumper` cannot create missing directories in the `outputPath` path.

### To Reproduce

1. Remove `tmp_test`
2. Run `benchmark/wave_dump_benchmark.dart`

### Expected behavior

The missing directories will be created.

### Actual behavior

Missing directories are not created, resulting in an exception.

### Additional: Dart SDK info

Dart SDK version: 2.19.3 (stable) (Tue Feb 28 15:52:19 2023 +0000) on "linux_x64"

### Additional: Context

ROHD v0.4.2

**Comment by mkorbel1** [comment]
Thank you for filing!
