### ISSUE TITLE
Wave dumping with `LogicArray`s and `LogicStructure`s

### ISSUE THREAD

**Issue by mkorbel1** [intel/rohd#384]
### Motivation

#375 introduced `LogicArray`s and `LogicStructure`s, but did not test or consider the `WaveDumper`.  There are likely some modifications necessary, and definitely some tests required.

### Desired solution

Write tests for the `WaveDumper` considering different scenarios of `LogicArray` and `LogicStructure` and implement necessary upgrades to make everything work right.

**Comment by mjayasim9** [comment]
Will work on this!

**Comment by mjayasim9** [comment]
The example below shows the VCD file generated for a test with `LogicArray`

![c765d2cf-850f-47d7-ac12-548e854c4af1](https://github.com/intel/rohd/assets/90426459/b70d3acf-83e6-4be3-a2d7-5a615f79c4fe)
 

![8d10fac7-0c87-4507-a1e7-6068e1208e88](https://github.com/intel/rohd/assets/90426459/dfe53847-c1c5-44e4-97d5-2107e94b5de6)

VCD currently does not support `LogicArray` representation (https://github.com/verilator/verilator/issues/3167) and therefore, we can close this issue for now. An alternate solution would be to split the bus by arrays, however, that would create numerous waves and it would be hard to view them unless there is a search option in the Wave Viewer.

**Comment by mkorbel1** [comment]
Thanks for looking into all this @mjayasim9!  Yes, we can close this for now since VCD doesn't seem to have any nice support for arrays anyways.
