### ISSUE TITLE
Add reset signal to `FlipFlop`

### ISSUE THREAD

**Issue by mkorbel1** [intel/rohd#69]
## Motivation
It would be nice to use `FlipFlop` with a reset signal (optionally synchronous or asynchronous)

## Desired solution
Add optional named parameter(s) to `FlipFlop` that, when specified, add reset behavior.

## Alternatives considered  
People can already achieve this using the `Sequential` block, but `FlipFlop` is convenient.

**Comment by stephtancs** [comment]
i can do this

**Comment by mkorbel1** [comment]
While we're at it, we should really make `d` and `clk` private in `FlipFlop`
