### ISSUE TITLE
Create an `equalsAnyOf` type of synthesizable function

### ISSUE THREAD

**Issue by mkorbel1** [intel/rohd#7]
A convenient operation to check if one `Logic` is currently equal to any of a list of other `Logic`s, which synthesizes safely to hardware.  The operation could be called `equalsAnyOf` or `isIn` or something else like that.

**Comment by RPG-coder-intc** [comment]
Hey Max, I will work on this next!

**Comment by RPG-coder-intc** [comment]
`equalsAnyOf` or `isIn` will be made for following datatype:
1. LogicValues only
2. Logic only
3. mix of LogicValues and Logic
5. int, bool, BigInt
