### ISSUE TITLE
Add operations for sign and zero extending

### ISSUE THREAD

**Issue by mkorbel1** [intel/rohd#83]
## Motivation
Padding width of signals (either signed or unsigned) is a bit too verbose.  It would be nice to be able to extend/pad `Logic` and `LogicValues`.

## Desired solution
Operation on `Logic` and `LogicValues` that return zero extended and sign extended versions with larger width.

## Alternatives considered  
Existing solution requires using something like `swizzle`.

**Comment by saw235** [comment]
Logic signExtend(Logic sig, int width) {
    if (sig.width > width) {
      throw Exception('Signal original width is higher than extended width');
    }

    Logic retsig = Logic(width: width);
    Logic msb = sig[sig.width];
    int padNum = width - sig.width; 

    List<Logic> swizzle = List.filled(padNum, msb) + [sig];
    retsig <= swizzle.swizzle(); 
    return retsig; 
  }

**Comment by saw235** [comment]
```dart
  Logic zeroExtend(Logic sig, int width) {
    if (sig.width > width) {
      throw Exception('Signal original width is higher than extended width');
    }

    Logic retsig = Logic(width: width);
    Logic msb = Const(0);
    int padNum = width - sig.width; 

    List<Logic> swizzle = List.filled(padNum, msb) + [sig];
    retsig <= swizzle.swizzle(); 
    return retsig; 
  }
  ```

**Comment by mkorbel1** [comment]
might be nice to implement this with a solution from #101
